# Generated by Django 6.0.1 on 2026-02-05 14:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Admin', 'Admin')], default='Student', max_length=20)),
                ('institute', models.CharField(default='IITRAM', max_length=20)),
                ('phone_no', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('faculty_id', models.CharField(editable=False, max_length=11, unique=True)),
                ('gender', models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('aadhar_no', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('graduation_level', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('PHD', 'PHD')], max_length=50)),
                ('photo_faculty', models.ImageField(blank=True, null=True, upload_to='pf/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('creadted_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('COMPUTER', 'Computer'), ('CIVIL', 'Civil'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollemet_no', models.CharField(editable=False, max_length=11, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('father_contact_no', models.CharField(max_length=15)),
                ('father_email', models.EmailField(max_length=254)),
                ('branch', models.CharField(choices=[('COMPUTER', 'Computer'), ('CIVIL', 'Civil'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')], max_length=15)),
                ('aadhar_no', models.IntegerField(unique=True)),
                ('is_tfws', models.BooleanField(default=False)),
                ('cast_catogry', models.CharField(choices=[('GEN', 'Gen'), ('OBC', 'Obc'), ('SC', 'Sc'), ('ST', 'St')], max_length=4)),
                ('admission_through', models.CharField(choices=[('ACPC', 'ACPC'), ('JOSAA', 'JOSAA')], max_length=10)),
                ('admission_heads', models.CharField(default='B.Tech', max_length=40)),
                ('level', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('PHD', 'PHD')], max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('creadted_at', models.DateTimeField(auto_now=True)),
                ('photo_student', models.ImageField(blank=True, null=True, upload_to='sp/')),
                ('leaving_certificate', models.FileField(upload_to='lc/')),
                ('attendence', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=1)),
                ('spi', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cpi', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scredits', models.DecimalField(decimal_places=1, max_digits=4)),
                ('name', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=150)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.student')),
            ],
        ),
        migrations.CreateModel(
            name='TestExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('COMPUTER', 'Computer'), ('CIVIL', 'Civil'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')], max_length=15)),
                ('test_date', models.DateTimeField()),
                ('syllabus', models.TextField()),
                ('total_marks', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('te_type', models.CharField(choices=[('Test', 'test'), ('Exam', 'exam')], max_length=5, verbose_name='type')),
                ('test_id', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_creator', to='sms.faculty')),
                ('en_student', models.ManyToManyField(related_name='enrolled_student', to='sms.student')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.IntegerField()),
                ('studentr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.student')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms.testexam')),
            ],
        ),
    ]
