# Generated by Django 6.0.1 on 2026-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
