# Generated by Django 6.0.1 on 2026-02-04 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollemet_no', models.CharField(editable=False, max_length=11, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('father_contact_no', models.CharField(max_length=15)),
                ('father_email', models.EmailField(max_length=254)),
                ('branch', models.CharField(choices=[('COMPUTER', 'Computer'), ('CIVIL', 'Civil'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')])),
                ('aadhar_no', models.IntegerField(max_length=12)),
                ('is_tfws', models.BooleanField(default=False)),
                ('cast_catogry', models.CharField(choices=[('GEN', 'Gen'), ('OBC', 'Obc'), ('SC', 'Sc'), ('ST', 'St')])),
                ('admission_through', models.CharField(choices=[('ACPC', 'ACPC'), ('JOSAA', 'JOSAA')], max_length=10)),
                ('admission_heads', models.CharField(default='B.Tech', max_length=40)),
                ('level', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('PHD', 'PHD')], max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('creadted_at', models.DateTimeField(auto_now=True)),
                ('photo_student', models.ImageField(blank=True, null=True, upload_to='sp/')),
                ('leaving_certificate', models.FileField(upload_to='lc/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
