# Generated by Django 6.0.1 on 2026-02-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_customuser_phone_no_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_no',
            field=models.IntegerField(unique=True),
        ),
    ]
