# Generated by Django 6.0.1 on 2026-02-05 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_student_aadhar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.CharField(choices=[('Computer Programming', 'CP'), ('Machine Learning', 'ML'), ('Data Science', 'DS'), ('App Developement', 'AP'), ('Web Developement', 'WD')], default='CP', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('COMPUTER', 'Computer'), ('CIVIL', 'Civil'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')], max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='cast_catogry',
            field=models.CharField(choices=[('GEN', 'Gen'), ('OBC', 'Obc'), ('SC', 'Sc'), ('ST', 'St')], max_length=4),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(choices=[('Computer Programming', 'CP'), ('Machine Learning', 'ML'), ('Data Science', 'DS'), ('App Developement', 'AP'), ('Web Developement', 'WD')], max_length=50)),
                ('salary', models.IntegerField()),
                ('faculty_id', models.CharField(editable=False, max_length=11, unique=True)),
                ('gender', models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('aadhar_no', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('graduation_level', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('PHD', 'PHD')], max_length=50)),
                ('photo_faculty', models.ImageField(blank=True, null=True, upload_to='pf/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('creadted_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('COMPUTER', 'Computer'), ('CIVIL', 'Civil'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('COMPUTER', 'Computer'), ('CIVIL', 'Civil'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')])),
                ('test_date', models.DateTimeField()),
                ('syllabus', models.TextField()),
                ('total_marks', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('te_type', models.CharField(choices=[('Test', 'test'), ('Exam', 'exam')], max_length=5, verbose_name='type')),
                ('test_id', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_creator', to='sms.faculty')),
                ('en_student', models.ManyToManyField(related_name='enrolled_student', to='sms.student')),
            ],
        ),
    ]
