# Generated by Django 5.1.5 on 2026-02-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_customuser_id_alter_student_branch_and_more'),
        ('sms', '0004_student_subjects_alter_student_branch_and_more'),
    ]

    operations = [
    ]
