# Generated by Django 5.1.5 on 2026-02-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_merge_20260205_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexam',
            name='department',
            field=models.CharField(choices=[('COMPUTER', 'Computer'), ('CIVIL', 'Civil'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical')], max_length=15),
        ),
        migrations.AlterField(
            model_name='testexam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
